name: Terraform Plan

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{secrets.TF_ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.TF_ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.TF_ARM_TENANT_ID}}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_working_dir: 'terraform'
          tf_actions_subcommand: "init"
          args: -var="client_secret=${{ secrets.TF_ARM_CLIENT_SECRET }}"
                -var="client_id=${{ secrets.TF_ARM_CLIENT_ID }}"
                -var="tenant_id=${{ secrets.TF_ARM_TENANT_ID }}"
                -var="sub=${{ secrets.TF_ARM_SUBSCRIPTION_ID }}"

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan


